<?php

use yii\db\Migration;

/**
 * Audit log for every Fahras verdict request issued by Tayseer.
 *
 * Each row corresponds to ONE call to FahrasService::check() — both
 * successful verdicts and transport/HTTP failures are logged so that:
 *   • The compliance officer can prove a check was made.
 *   • Managers can review every override (who, when, why).
 *   • Ops can correlate Tayseer audit rows with Fahras `activity_log`
 *     using the `request_id` (UUID v4 generated by the Fahras endpoint).
 */
class m260420_100000_create_fahras_check_log extends Migration
{
    public function safeUp()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable('{{%fahras_check_log}}', [
            'id'                => $this->bigPrimaryKey(),

            // Who initiated the check (null for CLI / system jobs).
            'user_id'           => $this->integer()->null(),

            // The Tayseer customer record this check is associated with.
            // Filled by actionFinish() once the customer is persisted; null
            // for live wizard checks that never resulted in a save.
            'customer_id'       => $this->integer()->null(),

            // Subject of the check.
            'id_number'         => $this->string(20)->notNull(),
            'name'              => $this->string(255)->null(),
            'phone'             => $this->string(30)->null(),

            // Verdict from Fahras (or 'error' on transport failure).
            // Stored as VARCHAR (not ENUM) so future verdict types
            // ("conditional_sell" etc.) can be added without altering the schema.
            'verdict'           => $this->string(20)->notNull(),
            'reason_code'       => $this->string(60)->null(),
            'reason_ar'         => $this->text()->null(),

            // Full payload as returned by Fahras (matches[], remote_errors[]).
            'matches_json'      => $this->json()->null(),

            // Override metadata: when set, a privileged user bypassed
            // a `cannot_sell` verdict — record who and why for audit.
            'override_user_id'  => $this->integer()->null(),
            'override_reason'   => $this->text()->null(),

            // Transport diagnostics for incident triage.
            'http_status'       => $this->smallInteger()->null(),
            'request_id'        => $this->char(36)->null(),
            'duration_ms'       => $this->integer()->null(),
            'from_cache'        => $this->boolean()->notNull()->defaultValue(false),

            // Where in the wizard the check ran (e.g. "step1", "finish", "manual").
            'source'            => $this->string(20)->null(),

            'created_at'        => $this->integer()->notNull(),
        ], $tableOptions);

        $this->createIndex('idx-fahras_check_log-id_number',  '{{%fahras_check_log}}', 'id_number');
        $this->createIndex('idx-fahras_check_log-verdict',    '{{%fahras_check_log}}', 'verdict');
        $this->createIndex('idx-fahras_check_log-created_at', '{{%fahras_check_log}}', 'created_at');
        $this->createIndex('idx-fahras_check_log-user_id',    '{{%fahras_check_log}}', 'user_id');
        $this->createIndex('idx-fahras_check_log-customer',   '{{%fahras_check_log}}', 'customer_id');
        $this->createIndex('idx-fahras_check_log-request_id', '{{%fahras_check_log}}', 'request_id');
    }

    public function safeDown()
    {
        $this->dropTable('{{%fahras_check_log}}');
    }
}
